apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ldap-ui
  namespace: public-service
spec:
  rules:
  - host: phpldap.c8cbbb54620274052be5ac0f932202e3a.cn-beijing.alicontainer.com
    http:
      paths:
      - backend:
          serviceName: phpldapadmin
          servicePort: 8080
